version: '2'
services:
  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"
    volumes:
      - /path/to/redis-persistence:/bitnami/redis
    restart: always

  mongo:
   image: mongo
   ports:
     - "27017:27017"
   restart: always


